Update check.yml

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -26,23 +26,25 @@ jobs:
       - name: Get Latest Release
         id: latest
         run:
-          eecho "version=$(gh release list --repo actions/runner -L 1 | awk '{print $1}')" >> $GITHUB_OUTPUT
+          echo "version=$(gh release list --repo actions/runner -L 1 | awk '{print $1}')" >> $GITHUB_OUTPUT
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   confirm:
     runs-on: ubuntu-latest
     needs: check
     steps:
-    - run: |
-        echo ${{ needs.check.outputs.current }}
-        echo ${{ needs.check.outputs.latest }}
-        if [[ ${{ needs.check.outputs.latest }} > ${{ needs.check.outputs.current }} ]];
-        then
-          echo "Update available for ${REPO}";
-        else
-          echo "No update required for ${REPO}";
-          exit 1
-        fi;
-    - name: create issue request
-      run: |
-        gh issue create --title "Update ${REPO}" --body "See https://github.com/${REPO}/releases/latest" --assignee "@paulstakem"
-      env:
+      - run: |
+          echo ${{ needs.check.outputs.current }}
+          echo ${{ needs.check.outputs.latest }}
+          if [[ ${{ needs.check.outputs.latest }} > ${{ needs.check.outputs.current }} ]];
+          then
+            echo "Update available for ${REPO}";
+          else
+            echo "No update required for ${REPO}";
+            exit 1
+          fi;
+      - name: create issue request
+        run: |
+          gh issue create --title "Update ${REPO}" --body "See https://github.com/${REPO}/releases/latest" --assignee "@paulstakem"
+        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
